version: '3.9'

services:
  postgres:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      - POSTGRES_USER=thquan
      - POSTGRES_PASSWORD=123zxc
      - POSTGRES_DB=storefront
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
